import React, { createContext, useState } from "react";
import { MainRouter } from "../../MainRouter";

import multicoloredArmlessTop from "./DataAssets/Clothes/MulticoloredArmlessTop.jpg";

// =============== ACCESSORY ============= //
import MoonAndStarNeckpiece from "./DataAssets/Accessories/MoonAndStarNeckpiece.png";
import TambourineCrossbodyBag from "./DataAssets/Accessories/Tambourine Crossbody Bag .png";
import KatyPerryKillerQueenEDP from "./DataAssets/Accessories/Katy Perry Killer Queen EDP.png";
import NerdyOvalGlasses from "./DataAssets/Accessories/Nerdy oval glasses.png";
import DiamondLadiesRing from "./DataAssets/Accessories/DiamondLadiesRing.jpg";
import GreyBeeWristWatch from "./DataAssets/Accessories/GreyBeeWrist-watch.png";
import SummerHandbag from "./DataAssets/Accessories/Summer Handbag.png";
import CasualBaseballCap from "./DataAssets/Accessories/CasualBaseballCap.jpg";
import TearDropStoneNecklace from "./DataAssets/Accessories/Tear-dropStoneNecklace.jpg";
import LadiesLuxuryWatch from "./DataAssets/Accessories/Ladies luxury watch.png";
import PatternClothFaceMask from "./DataAssets/Accessories/PatternClothFaceMask.jpg";
import FashionLadiesWatch from "./DataAssets/Accessories/FashionLadiesWatch.jpg";
import BlackLadiesBackpack from "./DataAssets/Accessories/BlackLadiesBackpack.jpg";

// =============== all ============= //
import RedLightweightGown from "./DataAssets/Clothes/RedLightweightGown.jpg";
import BlueBottonDownGown from "./DataAssets/Clothes/BlueBotton-downGown.jpg";
import LadiesBushPants from "./DataAssets/Clothes/LadiesBushPants.jpg";
import CheckedLadiesTrouser from "./DataAssets/Clothes/CheckedLadiesTrouser.jpg";
import BeanieWinterFleece from "./DataAssets/Clothes/Beanie winter fleece.png";
import MiniSkirt from "./DataAssets/Clothes/MiniSkirt.jpg";
import TopWithPleatedSkirtSatin from "./DataAssets/Clothes/TopWithPleatedSkirtSatin.jpg";
import WinterWarmWoolenParka from "./DataAssets/Clothes/WinterWarmWoolenParka.jpg";
import SummerDressForWomen from "./DataAssets/Clothes/SummerDressForWomen.jpg";
import WomenOfficeSuit from "./DataAssets/Clothes/WomenOfficeSuit.jpg";
import SingleBreastedCamiTop from "./DataAssets/Clothes/SingleBreastedCamiTop.jpg";
import TwillPaperBagTrousers from "./DataAssets/Clothes/TwillPaperBagTrousers.jpg";

// =============== SHOES ============= //
import guilherminaEmbellishedSlides from "./DataAssets/Shoes/Guilhermina Embellished Slides.png";
import SupergaPlaidSneakers from "./DataAssets/Shoes/Superga Plaid Sneakers.png";
import highHeelsLadiesShoes from "./DataAssets/Shoes/High heels ladies shoes.png";
import kedsSneakers from "./DataAssets/Shoes/Keds Champion Sneakers.png";
import SummerShoes from "./DataAssets/Shoes/Summer shoes.png";
import CasualFlatLoafers from "./DataAssets/Shoes/Casual Flat Loafers.png";
import BlackStrappyPeeptoe from "./DataAssets/Shoes/Black strappy peeptoe.png";
import SupergaPlatformSneakers from "./DataAssets/Shoes/Superga Platform Sneakers.png";
import HeeledSandals from "./DataAssets/Shoes/Heeled sandals.png";
import HAJINKBoatShoes from "./DataAssets/Shoes/Heeled sandals.png";
import CasualFlatSandals from "./DataAssets/Shoes/Casual Flat Sandals.png";
import SummerCorkSlippers from "./DataAssets/Shoes/Summer Cork Slippers.png";
import AnkleBoots from "./DataAssets/Shoes/Ankle boots.png";
import { toast } from "react-toastify";

export const DataContext = createContext();

export function Data() {
  const [Cart, setCart] = useState([]);
  const [favorite, setFavorite] = useState([]);
  const [signIn, setSignIn] = useState({});
  const [inspection, setInspection] = useState({});
  const [DeliveryOrder, setDeliveryOrder] = useState([]);
  const [Order, setOrder] = useState([]);
  const [Checkout, setCheckout] = useState([]);
  const [discount, setDiscount] = useState(false);
  const [search, setSearch] = useState("");
    const [data, setData] = useState(
      JSON.parse(localStorage.getItem("address")) || []
    );

  const [user, setUser] = useState({
    id: "",
    name: "",
    surname: "",
    email: "",
    address: "",
    state: "",
    city: "",
    phone: "",
  });
  const [address, setAddress] = useState({
    id: user.id,
    name: user.name,
    surname: user.surname,
    email: user.email,
    address: user.address,
    state: user.state,
    city: user.city,
    phone: user.phone,
  });

  const AddCart = (item) => {
    if (Cart.filter((fil) => fil.id === item.id).length === 0) {
      setCart([...Cart, { ...item }]);
      toast.success("product added to the cart :)");
    } else {
      Cart.filter((fil) => (fil.id === item.id ? fil.count++ : ""));
    }
  };

  const AddFavorite = (item) => {
    if (favorite.filter((fil) => fil.id === item.id).length === 0) {
      setFavorite([...favorite, { ...item }]);
      item.like = true;
    } else {
      setFavorite((favorite) => favorite.filter((fil) => fil.id !== item.id));
      item.like = false;
    }
  };
  return (
    <DataContext.Provider
      value={{
        setAddress,
        address,
        signIn,
        setSignIn,
        inspection,
        setInspection,
        favorite,
        setFavorite,
        StoreData,
        Cart,
        setCart,
        DeliveryOrder,
        setDeliveryOrder,
        Order,
        setOrder,
        data,
        setData,
        Checkout,
        setCheckout,
        discount,
        setDiscount,
        user,
        setUser,
        search,
        setSearch,
        AddCart,
        AddFavorite,
      }}
    >
      <MainRouter />
    </DataContext.Provider>
  );
}

const StoreData = [
  {
    id: 0,
    name: "Multicolored armless top",
    productImg: multicoloredArmlessTop,
    type: "clothes",
    category: "tops",
    color: "gold",
    size: "L",
    totalPrice: 1000,
    subPrice: 0,
    count: 1,
    moreSeen: 6,
    like: false,
    bestSeling: 5,
  },
  {
    id: 1,
    name: "Grey bee wrist-watch",
    productImg: GreyBeeWristWatch,
    type: "accessory",
    category: "watches",
    color: "gold",
    size: "M",
    totalPrice: 20000,
    subPrice: 0,
    count: 1,
    moreSeen: 11,
    like: false,
    bestSeling: 3,
  },
  {
    id: 2,
    name: "Mini skirt",
    productImg: MiniSkirt,
    type: "clothes",
    category: "shorts",
    color: "brown",
    size: "S",
    totalPrice: 2000,
    subPrice: 0,
    count: 1,
    moreSeen: 10,
    like: false,
    bestSeling: 4,
  },
  {
    id: 3,
    name: "Red lightweight gown",
    productImg: RedLightweightGown,
    type: "clothes",
    category: "dresses",
    color: "red",
    size: "XL",
    totalPrice: 10000,
    subPrice: 0,
    count: 1,
    moreSeen: 20,
    like: false,
    bestSeling: 5,
  },
  {
    id: 4,
    name: "Blue botton-down gown",
    productImg: BlueBottonDownGown,
    type: "clothes",
    category: "tops",
    color: "blue",
    size: "32",
    totalPrice: 15000,
    subPrice: 0,
    count: 1,
    moreSeen: 20,
    like: false,
    bestSeling: 4,
  },
  {
    id: 5,
    name: "Moon and star neckpiece",
    productImg: MoonAndStarNeckpiece,
    type: "accessory",
    category: "jewelry",
    color: "beige",
    size: "8",
    totalPrice: 35000,
    subPrice: 0,
    count: 1,
    moreSeen: 30,
    like: false,
    bestSeling: 3,
  },
  {
    id: 6,
    name: "Tambourine Crossbody Bag",
    productImg: TambourineCrossbodyBag,
    type: "accessory",
    category: "handbags",
    color: "black",
    size: "28",
    totalPrice: 8000,
    subPrice: 0,
    count: 1,
    moreSeen: 50,
    like: false,
    bestSeling: 4,
  },
  {
    id: 7,
    name: "Katy Perry Killer Queen EDP",
    productImg: KatyPerryKillerQueenEDP,
    type: "accessory",
    category: "fragrances",
    color: "red",
    size: "XL",
    totalPrice: 12000,
    subPrice: 0,
    count: 1,
    moreSeen: 30,
    like: false,
    bestSeling: 2,
  },
  {
    id: 8,
    name: "High heels ladies shoes",
    productImg: highHeelsLadiesShoes,
    type: "shoes",
    category: "heels",
    color: "brown",
    size: "42/10.5",
    totalPrice: 6000,
    subPrice: 0,
    count: 1,
    moreSeen: 25,
    like: false,
    bestSeling: 3,
  },
  {
    id: 9,
    name: "Nerdy oval glasses",
    productImg: NerdyOvalGlasses,
    type: "accessory",
    category: "glasses",
    color: "pink",
    size: "S",
    totalPrice: 3000,
    subPrice: 0,
    count: 1,
    moreSeen: 29,
    like: false,
    bestSeling: 4,
  },
  {
    id: 10,
    name: "Diamond ladies ring",
    productImg: DiamondLadiesRing,
    type: "accessory",
    category: "jewelry",
    color: "gold",
    size: "M",
    totalPrice: 150000,
    subPrice: 0,
    count: 1,
    moreSeen: 58,
    like: false,
    bestSeling: 2,
  },
  {
    id: 11,
    name: "Ladies bush pants",
    productImg: LadiesBushPants,
    type: "clothes",
    category: "jeans",
    color: "orange",
    size: "XL",
    totalPrice: 8500,
    subPrice: 0,
    count: 1,
    moreSeen: 49,
    like: false,
    bestSeling: 5,
  },
  {
    id: 12,
    name: "Guilhermina Embellished Slides",
    productImg: guilherminaEmbellishedSlides,
    type: "shoes",
    category: "slides",
    color: "orange",
    size: "40/7.5",
    totalPrice: 7500,
    subPrice: 0,
    count: 1,
    moreSeen: 41,
    like: false,
    bestSeling: 4,
  },
  {
    id: 13,
    name: "Superga Plaid Sneakers",
    productImg: SupergaPlaidSneakers,
    type: "shoes",
    category: "sneakers",
    color: "red",
    size: "36/5.5",
    totalPrice: 10500,
    subPrice: 0,
    count: 1,
    moreSeen: 29,
    like: false,
    bestSeling: 5,
  },
  {
    id: 14,
    name: "Checked ladies trouser",
    productImg: CheckedLadiesTrouser,
    type: "clothes",
    category: "pants",
    color: "taupe",
    size: "28",
    totalPrice: 11500,
    subPrice: 0,
    count: 1,
    moreSeen: 60,
    like: false,
    bestSeling: 2,
  },
  {
    id: 15,
    name: "Beanie winter fleece",
    productImg: BeanieWinterFleece,
    type: "accessory",
    category: "beanies",
    color: "black",
    size: "27",
    totalPrice: 9200,
    subPrice: 0,
    count: 1,
    moreSeen: 63,
    like: false,
    bestSeling: 4,
  },
  {
    id: 16,
    name: "Top with Pleated Skirt Satin",
    productImg: TopWithPleatedSkirtSatin,
    type: "clothes",
    category: "tops",
    color: "beige",
    size: "L",
    totalPrice: 8400,
    subPrice: 0,
    count: 1,
    moreSeen: 33,
    like: false,
    bestSeling: 4,
  },
  {
    id: 17,
    name: "Keds sneakers",
    productImg: kedsSneakers,
    type: "shoes",
    category: "sneakers",
    color: "taupe",
    size: "39/7.5",
    totalPrice: 14400,
    subPrice: 0,
    count: 1,
    moreSeen: 49,
    like: false,
    bestSeling: 5,
  },
  {
    id: 18,
    name: "Winter Warm Woolen Parka",
    productImg: WinterWarmWoolenParka,
    type: "clothes",
    category: "tops",
    color: "red",
    size: "L",
    totalPrice: 18400,
    subPrice: 0,
    count: 1,
    moreSeen: 64,
    like: false,
    bestSeling: 5,
  },
  {
    id: 19,
    name: "Summer Handbag",
    productImg: SummerHandbag,
    type: "accessory",
    category: "handbags",
    color: "pink",
    size: "S",
    totalPrice: 8400,
    subPrice: 0,
    count: 1,
    moreSeen: 32,
    like: false,
    bestSeling: 3,
  },

  // =========================================

  {
    id: 20,
    name: "Summer Dress for Women",
    productImg: SummerDressForWomen,
    type: "clothes",
    category: "dresses",
    color: "blue",
    size: "29",
    totalPrice: 10800,
    subPrice: 0,
    count: 1,
    moreSeen: 78,
    like: false,
    bestSeling: 5,
  },
  {
    id: 21,
    name: "Casual baseball cap",
    productImg: CasualBaseballCap,
    type: "accessory",
    category: "beanies",
    color: "red",
    size: "6",
    totalPrice: 5000,
    subPrice: 0,
    count: 1,
    moreSeen: 36,
    like: false,
    bestSeling: 1,
  },
  {
    id: 22,
    name: "Summer shoes",
    productImg: SummerShoes,
    type: "shoes",
    category: "flats",
    color: "brown",
    size: "39.5/8",
    totalPrice: 6000,
    subPrice: 0,
    count: 1,
    moreSeen: 30,
    like: false,
    bestSeling: 4,
  },
  {
    id: 23,
    name: "Women office suit",
    productImg: WomenOfficeSuit,
    type: "clothes",
    category: "dresses",
    color: "taupe",
    size: "XL",
    totalPrice: 30000,
    subPrice: 0,
    count: 1,
    moreSeen: 60,
    like: false,
    bestSeling: 3,
  },
  {
    id: 24,
    name: "Black strappy peeptoe",
    productImg: BlackStrappyPeeptoe,
    type: "shoes",
    category: "partyshoes",
    color: "black",
    size: "42/11",
    totalPrice: 10000,
    subPrice: 0,
    count: 1,
    moreSeen: 50,
    like: false,
    bestSeling: 4,
  },
  {
    id: 25,
    name: "Casual Flat Loafers",
    productImg: CasualFlatLoafers,
    type: "shoes",
    category: "sneakers",
    color: "orange",
    size: "42/10.5",
    totalPrice: 30000,
    subPrice: 0,
    count: 1,
    moreSeen: 64,
    like: false,
    bestSeling: 3,
  },
  {
    id: 26,
    name: "Twill paper bag trousers",
    productImg: TwillPaperBagTrousers,
    type: "clothes",
    category: "pants",
    color: "blue",
    size: "XXL",
    totalPrice: 20000,
    subPrice: 0,
    count: 1,
    moreSeen: 54,
    like: false,
    bestSeling: 4,
  },
  {
    id: 27,
    name: "Heeled sandals",
    productImg: HeeledSandals,
    type: "shoes",
    category: "heels",
    color: "black",
    size: "38/7",
    totalPrice: 15000,
    subPrice: 0,
    count: 1,
    moreSeen: 39,
    like: false,
    bestSeling: 4,
  },
  {
    id: 28,
    name: "Tear-drop stone necklace",
    productImg: TearDropStoneNecklace,
    type: "accessory",
    category: "jewelry",
    color: "blue",
    size: "XL",
    totalPrice: 45000,
    subPrice: 0,
    count: 1,
    moreSeen: 70,
    like: false,
    bestSeling: 2,
  },
  {
    id: 29,
    name: "Ladies luxury watch",
    productImg: LadiesLuxuryWatch,
    type: "accessory",
    category: "watches",
    color: "gold",
    size: "L",
    totalPrice: 15000,
    subPrice: 0,
    count: 1,
    moreSeen: 60,
    like: false,
    bestSeling: 4,
  },
  {
    id: 30,
    name: "Superga Platform Sneakers",
    productImg: SupergaPlatformSneakers,
    type: "shoes",
    category: "sneakers",
    color: "black",
    size: "41.5/10",
    totalPrice: 25000,
    subPrice: 0,
    count: 1,
    moreSeen: 68,
    like: false,
    bestSeling: 5,
  },
  {
    id: 31,
    name: "HAJINK Boat Shoes",
    productImg: HAJINKBoatShoes,
    type: "shoes",
    category: "flats",
    color: "black",
    size: "38/7",
    totalPrice: 20000,
    subPrice: 0,
    count: 1,
    moreSeen: 68,
    like: false,
    bestSeling: 4,
  },
  {
    id: 32,
    name: "Fahian Ladies Watch",
    productImg: FashionLadiesWatch,
    type: "accessory",
    category: "watches",
    color: "black",
    size: "M",
    totalPrice: 50000,
    subPrice: 0,
    count: 1,
    moreSeen: 78,
    like: false,
    bestSeling: 5,
  },
  {
    id: 33,
    name: "Black ladies backpack",
    productImg: BlackLadiesBackpack,
    type: "accessory",
    category: "backpacks",
    color: "black",
    size: "7",
    totalPrice: 20000,
    subPrice: 0,
    count: 1,
    moreSeen: 58,
    like: false,
    bestSeling: 1,
  },
  {
    id: 34,
    name: "Casual Flat Sandals",
    productImg: CasualFlatSandals,
    type: "shoes",
    category: "sandals",
    color: "white",
    size: "37.5/6.5",
    totalPrice: 22000,
    subPrice: 0,
    count: 1,
    moreSeen: 38,
    like: false,
    bestSeling: 3,
  },
  {
    id: 35,
    name: "Pattern Cloth Face Mask",
    productImg: PatternClothFaceMask,
    type: "accessory",
    category: "facemask",
    color: "black",
    size: "8",
    totalPrice: 21000,
    subPrice: 0,
    count: 1,
    moreSeen: 60,
    like: false,
    bestSeling: 5,
  },
  {
    id: 36,
    name: "Summer Cork Slippers",
    productImg: SummerCorkSlippers,
    type: "shoes",
    category: "slides",
    color: "black",
    size: "42/11",
    totalPrice: 11000,
    subPrice: 0,
    count: 1,
    moreSeen: 70,
    like: false,
    bestSeling: 5,
  },
  {
    id: 37,
    name: "Ankle boots",
    productImg: AnkleBoots,
    type: "shoes",
    category: "booties",
    color: "brown",
    size: "43/12",
    totalPrice: 31000,
    subPrice: 0,
    count: 1,
    moreSeen: 70,
    like: false,
    bestSeling: 3,
  },
  {
    id: 38,
    name: "Single Breasted Cami Top",
    productImg: SingleBreastedCamiTop,
    type: "clothes",
    category: "tops",
    color: "white",
    size: "30",
    totalPrice: 18000,
    subPrice: 0,
    count: 1,
    moreSeen: 50,
    like: false,
    bestSeling: 5,
  },

  // =========================================

  {
    id: 39,
    name: "Summer Dress for Women",
    productImg: SummerDressForWomen,
    type: "clothes",
    category: "dresses",
    color: "blue",
    size: "29",
    totalPrice: 10800,
    subPrice: 0,
    count: 1,
    moreSeen: 78,
    like: false,
    bestSeling: 5,
  },
  {
    id: 40,
    name: "Casual baseball cap",
    productImg: CasualBaseballCap,
    type: "accessory",
    category: "beanies",
    color: "red",
    size: "6",
    totalPrice: 5000,
    subPrice: 0,
    count: 1,
    moreSeen: 36,
    like: false,
    bestSeling: 1,
  },
  {
    id: 41,
    name: "Summer shoes",
    productImg: SummerShoes,
    type: "shoes",
    category: "flats",
    color: "brown",
    size: "39.5/8",
    totalPrice: 6000,
    subPrice: 0,
    count: 1,
    moreSeen: 30,
    like: false,
    bestSeling: 4,
  },
  {
    id: 42,
    name: "Single Breasted Cami Top",
    productImg: SingleBreastedCamiTop,
    type: "clothes",
    category: "tops",
    color: "white",
    size: "30",
    totalPrice: 18000,
    subPrice: 0,
    count: 1,
    moreSeen: 50,
    like: false,
    bestSeling: 5,
  },
  {
    id: 43,
    name: "Women office suit",
    productImg: WomenOfficeSuit,
    type: "clothes",
    category: "dresses",
    color: "taupe",
    size: "XL",
    totalPrice: 30000,
    subPrice: 0,
    count: 1,
    moreSeen: 60,
    like: false,
    bestSeling: 3,
  },
  {
    id: 44,
    name: "Black strappy peeptoe",
    productImg: BlackStrappyPeeptoe,
    type: "shoes",
    category: "partyshoes",
    color: "black",
    size: "42/11",
    totalPrice: 10000,
    subPrice: 0,
    count: 1,
    moreSeen: 50,
    like: false,
    bestSeling: 4,
  },
  {
    id: 45,
    name: "Casual Flat Loafers",
    productImg: CasualFlatLoafers,
    type: "shoes",
    category: "sneakers",
    color: "orange",
    size: "42/10.5",
    totalPrice: 30000,
    subPrice: 0,
    count: 1,
    moreSeen: 64,
    like: false,
    bestSeling: 3,
  },
  {
    id: 46,
    name: "Twill paper bag trousers",
    productImg: TwillPaperBagTrousers,
    type: "clothes",
    category: "pants",
    color: "blue",
    size: "XXL",
    totalPrice: 20000,
    subPrice: 0,
    count: 1,
    moreSeen: 54,
    like: false,
    bestSeling: 4,
  },
  {
    id: 47,
    name: "Heeled sandals",
    productImg: HeeledSandals,
    type: "shoes",
    category: "heels",
    color: "black",
    size: "38/7",
    totalPrice: 15000,
    subPrice: 0,
    count: 1,
    moreSeen: 39,
    like: false,
    bestSeling: 4,
  },
  {
    id: 48,
    name: "Tear-drop stone necklace",
    productImg: TearDropStoneNecklace,
    type: "accessory",
    category: "jewelry",
    color: "blue",
    size: "XL",
    totalPrice: 45000,
    subPrice: 0,
    count: 1,
    moreSeen: 70,
    like: false,
    bestSeling: 2,
  },
  {
    id: 49,
    name: "Ladies luxury watch",
    productImg: LadiesLuxuryWatch,
    type: "accessory",
    category: "watches",
    color: "gold",
    size: "L",
    totalPrice: 15000,
    subPrice: 0,
    count: 1,
    moreSeen: 60,
    like: false,
    bestSeling: 4,
  },
  {
    id: 50,
    name: "Superga Platform Sneakers",
    productImg: SupergaPlatformSneakers,
    type: "shoes",
    category: "sneakers",
    color: "black",
    size: "41.5/10",
    totalPrice: 25000,
    subPrice: 0,
    count: 1,
    moreSeen: 68,
    like: false,
    bestSeling: 5,
  },
  {
    id: 51,
    name: "HAJINK Boat Shoes",
    productImg: HAJINKBoatShoes,
    type: "shoes",
    category: "flats",
    color: "black",
    size: "38/7",
    totalPrice: 20000,
    subPrice: 0,
    count: 1,
    moreSeen: 68,
    like: false,
    bestSeling: 4,
  },
  {
    id: 52,
    name: "Fahian Ladies Watch",
    productImg: FashionLadiesWatch,
    type: "accessory",
    category: "watches",
    color: "black",
    size: "M",
    totalPrice: 50000,
    subPrice: 0,
    count: 1,
    moreSeen: 78,
    like: false,
    bestSeling: 5,
  },
  {
    id: 53,
    name: "Black ladies backpack",
    productImg: BlackLadiesBackpack,
    type: "accessory",
    category: "backpacks",
    color: "black",
    size: "7",
    totalPrice: 20000,
    subPrice: 0,
    count: 1,
    moreSeen: 58,
    like: false,
    bestSeling: 1,
  },
  {
    id: 54,
    name: "Casual Flat Sandals",
    productImg: CasualFlatSandals,
    type: "shoes",
    category: "sandals",
    color: "white",
    size: "37.5/6.5",
    totalPrice: 22000,
    subPrice: 0,
    count: 1,
    moreSeen: 38,
    like: false,
    bestSeling: 3,
  },
  {
    id: 55,
    name: "Pattern Cloth Face Mask",
    productImg: PatternClothFaceMask,
    type: "accessory",
    category: "facemask",
    color: "black",
    size: "8",
    totalPrice: 21000,
    subPrice: 0,
    count: 1,
    moreSeen: 60,
    like: false,
    bestSeling: 5,
  },
  {
    id: 56,
    name: "Summer Cork Slippers",
    productImg: SummerCorkSlippers,
    type: "shoes",
    category: "slides",
    color: "black",
    size: "42/11",
    totalPrice: 11000,
    subPrice: 0,
    count: 1,
    moreSeen: 70,
    like: false,
    bestSeling: 5,
  },
  {
    id: 57,
    name: "Ankle boots",
    productImg: AnkleBoots,
    type: "shoes",
    category: "booties",
    color: "brown",
    size: "43/12",
    totalPrice: 31000,
    subPrice: 0,
    count: 1,
    moreSeen: 70,
    like: false,
    bestSeling: 3,
  },
  {
    id: 58,
    name: "Multicolored armless tops",
    productImg: multicoloredArmlessTop,
    type: "clothes",
    category: "tops",
    color: "gold",
    size: "L",
    totalPrice: 1000,
    subPrice: 0,
    count: 1,
    moreSeen: 6,
    like: false,
    bestSeling: 5,
  },
  // =========================== //
  {
    id: 59,
    name: "Grey bee wrist-watch",
    productImg: GreyBeeWristWatch,
    type: "accessory",
    category: "watches",
    color: "gold",
    size: "M",
    totalPrice: 20000,
    subPrice: 0,
    count: 1,
    moreSeen: 11,
    like: false,
    bestSeling: 3,
  },
  {
    id: 60,
    name: "Mini skirt",
    productImg: MiniSkirt,
    type: "clothes",
    category: "shorts",
    color: "brown",
    size: "S",
    totalPrice: 2000,
    subPrice: 0,
    count: 1,
    moreSeen: 10,
    like: false,
    bestSeling: 4,
  },
  {
    id: 61,
    name: "Red lightweight gown",
    productImg: RedLightweightGown,
    type: "clothes",
    category: "dresses",
    color: "red",
    size: "XL",
    totalPrice: 10000,
    subPrice: 0,
    count: 1,
    moreSeen: 20,
    like: false,
    bestSeling: 5,
  },
  {
    id: 62,
    name: "Blue botton-down gown",
    productImg: BlueBottonDownGown,
    type: "clothes",
    category: "tops",
    color: "blue",
    size: "32",
    totalPrice: 15000,
    subPrice: 0,
    count: 1,
    moreSeen: 20,
    like: false,
    bestSeling: 4,
  },
  {
    id: 63,
    name: "Moon and star neckpiece",
    productImg: MoonAndStarNeckpiece,
    type: "accessory",
    category: "jewelry",
    color: "beige",
    size: "8",
    totalPrice: 35000,
    subPrice: 0,
    count: 1,
    moreSeen: 30,
    like: false,
    bestSeling: 3,
  },
  {
    id: 64,
    name: "Tambourine Crossbody Bag",
    productImg: TambourineCrossbodyBag,
    type: "accessory",
    category: "handbags",
    color: "black",
    size: "28",
    totalPrice: 8000,
    subPrice: 0,
    count: 1,
    moreSeen: 50,
    like: false,
    bestSeling: 4,
  },
  {
    id: 65,
    name: "Katy Perry Killer Queen EDP",
    productImg: KatyPerryKillerQueenEDP,
    type: "accessory",
    category: "fragrances",
    color: "red",
    size: "XL",
    totalPrice: 12000,
    subPrice: 0,
    count: 1,
    moreSeen: 30,
    like: false,
    bestSeling: 2,
  },
  {
    id: 66,
    name: "High heels ladies shoes",
    productImg: highHeelsLadiesShoes,
    type: "shoes",
    category: "heels",
    color: "brown",
    size: "42/10.5",
    totalPrice: 6000,
    subPrice: 0,
    count: 1,
    moreSeen: 25,
    like: false,
    bestSeling: 3,
  },
  {
    id: 67,
    name: "Nerdy oval glasses",
    productImg: NerdyOvalGlasses,
    type: "accessory",
    category: "glasses",
    color: "pink",
    size: "S",
    totalPrice: 3000,
    subPrice: 0,
    count: 1,
    moreSeen: 29,
    like: false,
    bestSeling: 4,
  },
  {
    id: 68,
    name: "Diamond ladies ring",
    productImg: DiamondLadiesRing,
    type: "accessory",
    category: "jewelry",
    color: "gold",
    size: "M",
    totalPrice: 150000,
    subPrice: 0,
    count: 1,
    moreSeen: 58,
    like: false,
    bestSeling: 2,
  },
  {
    id: 69,
    name: "Ladies bush pants",
    productImg: LadiesBushPants,
    type: "clothes",
    category: "jeans",
    color: "orange",
    size: "XL",
    totalPrice: 8500,
    subPrice: 0,
    count: 1,
    moreSeen: 49,
    like: false,
    bestSeling: 5,
  },
  {
    id: 70,
    name: "Guilhermina Embellished Slides",
    productImg: guilherminaEmbellishedSlides,
    type: "shoes",
    category: "slides",
    color: "orange",
    size: "40/7.5",
    totalPrice: 7500,
    subPrice: 0,
    count: 1,
    moreSeen: 41,
    like: false,
    bestSeling: 4,
  },
  {
    id: 71,
    name: "Superga Plaid Sneakers",
    productImg: SupergaPlaidSneakers,
    type: "shoes",
    category: "sneakers",
    color: "red",
    size: "36/5.5",
    totalPrice: 10500,
    subPrice: 0,
    count: 1,
    moreSeen: 29,
    like: false,
    bestSeling: 5,
  },
  {
    id: 72,
    name: "Checked ladies trouser",
    productImg: CheckedLadiesTrouser,
    type: "clothes",
    category: "pants",
    color: "taupe",
    size: "28",
    totalPrice: 11500,
    subPrice: 0,
    count: 1,
    moreSeen: 60,
    like: false,
    bestSeling: 2,
  },
  {
    id: 73,
    name: "Beanie winter fleece",
    productImg: BeanieWinterFleece,
    type: "accessory",
    category: "beanies",
    color: "black",
    size: "27",
    totalPrice: 9200,
    subPrice: 0,
    count: 1,
    moreSeen: 63,
    like: false,
    bestSeling: 4,
  },
  {
    id: 74,
    name: "Top with Pleated Skirt Satin",
    productImg: TopWithPleatedSkirtSatin,
    type: "clothes",
    category: "tops",
    color: "beige",
    size: "L",
    totalPrice: 8400,
    subPrice: 0,
    count: 1,
    moreSeen: 33,
    like: false,
    bestSeling: 4,
  },
  {
    id: 75,
    name: "Keds sneakers",
    productImg: kedsSneakers,
    type: "shoes",
    category: "sneakers",
    color: "taupe",
    size: "39/7.5",
    totalPrice: 14400,
    subPrice: 0,
    count: 1,
    moreSeen: 49,
    like: false,
    bestSeling: 5,
  },
  {
    id: 76,
    name: "Winter Warm Woolen Parka",
    productImg: WinterWarmWoolenParka,
    type: "clothes",
    category: "tops",
    color: "red",
    size: "L",
    totalPrice: 18400,
    subPrice: 0,
    count: 1,
    moreSeen: 64,
    like: false,
    bestSeling: 5,
  },
  {
    id: 77,
    name: "Summer Handbag",
    productImg: SummerHandbag,
    type: "accessory",
    category: "handbags",
    color: "pink",
    size: "S",
    totalPrice: 8400,
    subPrice: 0,
    count: 1,
    moreSeen: 32,
    like: false,
    bestSeling: 3,
  },

  // =========================== //

  {
    id: 78,
    name: "Summer Dress for Women",
    productImg: SummerDressForWomen,
    type: "clothes",
    category: "dresses",
    color: "blue",
    size: "29",
    totalPrice: 10800,
    subPrice: 0,
    count: 1,
    moreSeen: 78,
    like: false,
    bestSeling: 5,
  },
  {
    id: 79,
    name: "Casual baseball cap",
    productImg: CasualBaseballCap,
    type: "accessory",
    category: "beanies",
    color: "red",
    size: "6",
    totalPrice: 5000,
    subPrice: 0,
    count: 1,
    moreSeen: 36,
    like: false,
    bestSeling: 1,
  },
  {
    id: 80,
    name: "Multicolored armless tops",
    productImg: multicoloredArmlessTop,
    type: "clothes",
    category: "tops",
    color: "gold",
    size: "L",
    totalPrice: 1000,
    subPrice: 0,
    count: 1,
    moreSeen: 6,
    like: false,
    bestSeling: 5,
  },
  {
    id: 81,
    name: "Summer shoes",
    productImg: SummerShoes,
    type: "shoes",
    category: "flats",
    color: "brown",
    size: "39.5/8",
    totalPrice: 6000,
    subPrice: 0,
    count: 1,
    moreSeen: 30,
    like: false,
    bestSeling: 4,
  },
  {
    id: 82,
    name: "Single Breasted Cami Top",
    productImg: SingleBreastedCamiTop,
    type: "clothes",
    category: "tops",
    color: "white",
    size: "30",
    totalPrice: 18000,
    subPrice: 0,
    count: 1,
    moreSeen: 50,
    like: false,
    bestSeling: 5,
  },
  {
    id: 83,
    name: "Women office suit",
    productImg: WomenOfficeSuit,
    type: "clothes",
    category: "dresses",
    color: "taupe",
    size: "XL",
    totalPrice: 30000,
    subPrice: 0,
    count: 1,
    moreSeen: 60,
    like: false,
    bestSeling: 3,
  },
  {
    id: 84,
    name: "Black strappy peeptoe",
    productImg: BlackStrappyPeeptoe,
    type: "shoes",
    category: "partyshoes",
    color: "black",
    size: "42/11",
    totalPrice: 10000,
    subPrice: 0,
    count: 1,
    moreSeen: 50,
    like: false,
    bestSeling: 4,
  },
  {
    id: 85,
    name: "Casual Flat Loafers",
    productImg: CasualFlatLoafers,
    type: "shoes",
    category: "sneakers",
    color: "orange",
    size: "42/10.5",
    totalPrice: 30000,
    subPrice: 0,
    count: 1,
    moreSeen: 64,
    like: false,
    bestSeling: 3,
  },
  {
    id: 86,
    name: "Twill paper bag trousers",
    productImg: TwillPaperBagTrousers,
    type: "clothes",
    category: "pants",
    color: "blue",
    size: "XXL",
    totalPrice: 20000,
    subPrice: 0,
    count: 1,
    moreSeen: 54,
    like: false,
    bestSeling: 4,
  },
  {
    id: 87,
    name: "Summer Cork Slippers",
    productImg: SummerCorkSlippers,
    type: "shoes",
    category: "slides",
    color: "black",
    size: "42/11",
    totalPrice: 11000,
    subPrice: 0,
    count: 1,
    moreSeen: 70,
    like: false,
    bestSeling: 5,
  },
  {
    id: 88,
    name: "Ankle boots",
    productImg: AnkleBoots,
    type: "shoes",
    category: "booties",
    color: "brown",
    size: "43/12",
    totalPrice: 31000,
    subPrice: 0,
    count: 1,
    moreSeen: 70,
    like: false,
    bestSeling: 3,
  },
  {
    id: 89,
    name: "Grey bee wrist-watch",
    productImg: GreyBeeWristWatch,
    type: "accessory",
    category: "watches",
    color: "gold",
    size: "M",
    totalPrice: 20000,
    subPrice: 0,
    count: 1,
    moreSeen: 11,
    like: false,
    bestSeling: 3,
  },
  {
    id: 90,
    name: "Mini skirt",
    productImg: MiniSkirt,
    type: "clothes",
    category: "shorts",
    color: "brown",
    size: "S",
    totalPrice: 2000,
    subPrice: 0,
    count: 1,
    moreSeen: 10,
    like: false,
    bestSeling: 4,
  },
  {
    id: 91,
    name: "Red lightweight gown",
    productImg: RedLightweightGown,
    type: "clothes",
    category: "dresses",
    color: "red",
    size: "XL",
    totalPrice: 10000,
    subPrice: 0,
    count: 1,
    moreSeen: 20,
    like: false,
    bestSeling: 5,
  },
  {
    id: 92,
    name: "Blue botton-down gown",
    productImg: BlueBottonDownGown,
    type: "clothes",
    category: "tops",
    color: "blue",
    size: "32",
    totalPrice: 15000,
    subPrice: 0,
    count: 1,
    moreSeen: 20,
    like: false,
    bestSeling: 4,
  },
  {
    id: 93,
    name: "Moon and star neckpiece",
    productImg: MoonAndStarNeckpiece,
    type: "accessory",
    category: "jewelry",
    color: "beige",
    size: "8",
    totalPrice: 35000,
    subPrice: 0,
    count: 1,
    moreSeen: 30,
    like: false,
    bestSeling: 3,
  },
  {
    id: 94,
    name: "Tambourine Crossbody Bag",
    productImg: TambourineCrossbodyBag,
    type: "accessory",
    category: "handbags",
    color: "black",
    size: "28",
    totalPrice: 8000,
    subPrice: 0,
    count: 1,
    moreSeen: 50,
    like: false,
    bestSeling: 4,
  },
  {
    id: 95,
    name: "Katy Perry Killer Queen EDP",
    productImg: KatyPerryKillerQueenEDP,
    type: "accessory",
    category: "fragrances",
    color: "red",
    size: "XL",
    totalPrice: 12000,
    subPrice: 0,
    count: 1,
    moreSeen: 30,
    like: false,
    bestSeling: 2,
  },
  {
    id: 96,
    name: "High heels ladies shoes",
    productImg: highHeelsLadiesShoes,
    type: "shoes",
    category: "heels",
    color: "brown",
    size: "42/10.5",
    totalPrice: 6000,
    subPrice: 0,
    count: 1,
    moreSeen: 25,
    like: false,
    bestSeling: 3,
  },
  {
    id: 97,
    name: "Nerdy oval glasses",
    productImg: NerdyOvalGlasses,
    type: "accessory",
    category: "glasses",
    color: "pink",
    size: "S",
    totalPrice: 3000,
    subPrice: 0,
    count: 1,
    moreSeen: 29,
    like: false,
    bestSeling: 4,
  },
  {
    id: 98,
    name: "Diamond ladies ring",
    productImg: DiamondLadiesRing,
    type: "accessory",
    category: "jewelry",
    color: "gold",
    size: "M",
    totalPrice: 150000,
    subPrice: 0,
    count: 1,
    moreSeen: 58,
    like: false,
    bestSeling: 2,
  },
  {
    id: 99,
    name: "Ladies bush pants",
    productImg: LadiesBushPants,
    type: "clothes",
    category: "jeans",
    color: "orange",
    size: "XL",
    totalPrice: 8500,
    subPrice: 0,
    count: 1,
    moreSeen: 49,
    like: false,
    bestSeling: 5,
  },
  {
    id: 100,
    name: "Guilhermina Embellished Slides",
    productImg: guilherminaEmbellishedSlides,
    type: "shoes",
    category: "slides",
    color: "orange",
    size: "40/7.5",
    totalPrice: 7500,
    subPrice: 0,
    count: 1,
    moreSeen: 41,
    like: false,
    bestSeling: 4,
  },
  {
    id: 101,
    name: "Superga Plaid Sneakers",
    productImg: SupergaPlaidSneakers,
    type: "shoes",
    category: "sneakers",
    color: "red",
    size: "36/5.5",
    totalPrice: 10500,
    subPrice: 0,
    count: 1,
    moreSeen: 29,
    like: false,
    bestSeling: 5,
  },
  {
    id: 102,
    name: "Checked ladies trouser",
    productImg: CheckedLadiesTrouser,
    type: "clothes",
    category: "pants",
    color: "taupe",
    size: "28",
    totalPrice: 11500,
    subPrice: 0,
    count: 1,
    moreSeen: 60,
    like: false,
    bestSeling: 2,
  },
  {
    id: 103,
    name: "Beanie winter fleece",
    productImg: BeanieWinterFleece,
    type: "accessory",
    category: "beanies",
    color: "black",
    size: "27",
    totalPrice: 9200,
    subPrice: 0,
    count: 1,
    moreSeen: 63,
    like: false,
    bestSeling: 4,
  },
  {
    id: 104,
    name: "Top with Pleated Skirt Satin",
    productImg: TopWithPleatedSkirtSatin,
    type: "clothes",
    category: "tops",
    color: "beige",
    size: "L",
    totalPrice: 8400,
    subPrice: 0,
    count: 1,
    moreSeen: 33,
    like: false,
    bestSeling: 4,
  },
  {
    id: 105,
    name: "Keds sneakers",
    productImg: kedsSneakers,
    type: "shoes",
    category: "sneakers",
    color: "taupe",
    size: "39/7.5",
    totalPrice: 14400,
    subPrice: 0,
    count: 1,
    moreSeen: 49,
    like: false,
    bestSeling: 5,
  },
  {
    id: 106,
    name: "Winter Warm Woolen Parka",
    productImg: WinterWarmWoolenParka,
    type: "clothes",
    category: "tops",
    color: "red",
    size: "L",
    totalPrice: 18400,
    subPrice: 0,
    count: 1,
    moreSeen: 64,
    like: false,
    bestSeling: 5,
  },
  {
    id: 107,
    name: "Summer Handbag",
    productImg: SummerHandbag,
    type: "accessory",
    category: "handbags",
    color: "pink",
    size: "S",
    totalPrice: 8400,
    subPrice: 0,
    count: 1,
    moreSeen: 32,
    like: false,
    bestSeling: 3,
  },
  {
    id: 108,
    name: "Tear-drop stone necklace",
    productImg: TearDropStoneNecklace,
    type: "accessory",
    category: "jewelry",
    color: "blue",
    size: "XL",
    totalPrice: 45000,
    subPrice: 0,
    count: 1,
    moreSeen: 70,
    like: false,
    bestSeling: 2,
  },
  {
    id: 109,
    name: "Ladies luxury watch",
    productImg: LadiesLuxuryWatch,
    type: "accessory",
    category: "watches",
    color: "gold",
    size: "L",
    totalPrice: 15000,
    subPrice: 0,
    count: 1,
    moreSeen: 60,
    like: false,
    bestSeling: 4,
  },
  {
    id: 110,
    name: "Superga Platform Sneakers",
    productImg: SupergaPlatformSneakers,
    type: "shoes",
    category: "sneakers",
    color: "black",
    size: "41.5/10",
    totalPrice: 25000,
    subPrice: 0,
    count: 1,
    moreSeen: 68,
    like: false,
    bestSeling: 5,
  },
  {
    id: 111,
    name: "HAJINK Boat Shoes",
    productImg: HAJINKBoatShoes,
    type: "shoes",
    category: "flats",
    color: "black",
    size: "38/7",
    totalPrice: 20000,
    subPrice: 0,
    count: 1,
    moreSeen: 68,
    like: false,
    bestSeling: 4,
  },
  {
    id: 112,
    name: "Fahian Ladies Watch",
    productImg: FashionLadiesWatch,
    type: "accessory",
    category: "watches",
    color: "black",
    size: "M",
    totalPrice: 50000,
    subPrice: 0,
    count: 1,
    moreSeen: 78,
    like: false,
    bestSeling: 5,
  },
  {
    id: 113,
    name: "Black ladies backpack",
    productImg: BlackLadiesBackpack,
    type: "accessory",
    category: "backpacks",
    color: "black",
    size: "7",
    totalPrice: 20000,
    subPrice: 0,
    count: 1,
    moreSeen: 58,
    like: false,
    bestSeling: 1,
  },
  {
    id: 114,
    name: "Casual Flat Sandals",
    productImg: CasualFlatSandals,
    type: "shoes",
    category: "sandals",
    color: "white",
    size: "37.5/6.5",
    totalPrice: 22000,
    subPrice: 0,
    count: 1,
    moreSeen: 38,
    like: false,
    bestSeling: 3,
  },
  {
    id: 115,
    name: "Pattern Cloth Face Mask",
    productImg: PatternClothFaceMask,
    type: "accessory",
    category: "facemask",
    color: "black",
    size: "8",
    totalPrice: 21000,
    subPrice: 0,
    count: 1,
    moreSeen: 60,
    like: false,
    bestSeling: 5,
  },
  {
    id: 116,
    name: "Heeled sandals",
    productImg: HeeledSandals,
    type: "shoes",
    category: "heels",
    color: "black",
    size: "38/7",
    totalPrice: 15000,
    subPrice: 0,
    count: 1,
    moreSeen: 39,
    like: false,
    bestSeling: 4,
  },
];
